# Default mission file

# initial_pose_x: float in meters
# initial_pose_y: float in meters
# initial_pose_a: float in radians (yaw)

kobuki_a:
  initial_pose_x:
  initial_pose_y:
  initial_pose_a:

kobuki_b:
  initial_pose_x:
  initial_pose_y:
  initial_pose_a:

kobuki_c:
  initial_pose_x:
  initial_pose_y:
  initial_pose_a:

kobuki_d:
  initial_pose_x:
  initial_pose_y:
  initial_pose_a:

kobuki_e:
  initial_pose_x:
  initial_pose_y:
  initial_pose_a: